[package]
name = "email-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mail-parser = "0.8.2"
serde_json = "1.0.96"
zip-extract = "0.1.2"
